if(WIN32)
    if(CMAKE_GENERATOR MATCHES "Win64")
      set(PLATFORM win64)
    else()
      set(PLATFORM win32)
    endif()
elseif(APPLE)
    if(CMAKE_OSX_ARCHITECTURES MATCHES "x86_64")
      set(PLATFORM osx64)
    else()
      set(PLATFORM osx32)
    endif()
elseif(UNIX)
    set(PLATFORM linux)
endif()